### ISSUE TITLE
Net::NTLM::VERSION missing

### ISSUE THREAD

**Issue by eugmill** [dandemeyere/responsys-api#31]
Hi folks. First, thanks for all the hard work on this gem. 

I seem to be getting this error

```
undefined method `to_hash' for #<NameError: uninitialized constant Net::NTLM::VERSION>
 /gems/ruby-2.1.4/gems/responsys-api-0.2.3/lib/responsys/helper.rb:68:in `format_response_with_errors'
 /gems/ruby-2.1.4/gems/responsys-api-0.2.3/lib/responsys/api/client.rb:26:in `rescue in block in api_method'
 /gems/ruby-2.1.4/gems/responsys-api-0.2.3/lib/responsys/api/client.rb:29:in `block in api_method'
 /gems/ruby-2.1.4/gems/responsys-api-0.2.3/lib/responsys/api/session_pool.rb:27:in `block in with'
 /gems/ruby-2.1.4/gems/connection_pool-2.1.3/lib/connection_pool.rb:62:in `with'
 /gems/ruby-2.1.4/gems/responsys-api-0.2.3/lib/responsys/api/session_pool.rb:26:in `with'
 /gems/ruby-2.1.4/gems/responsys-api-0.2.3/lib/responsys/api/client.rb:15:in `api_method'
 /gems/ruby-2.1.4/gems/responsys-api-0.2.3/lib/responsys/api/list.rb:25:in `merge_list_members'
```

It looks like it's related to Savon but I haven't dug too deep into it yet. Was wondering if anybody encountered it before. 

Adding a require to the responsys-api initializer resolves it.

**Comment by florrain** [comment]
Hi there,

I remember we had weird issues with Savon and that gem last year. Can't recall exactly why but we fixed it by adding the gem in the .gemspec.
We had a pull request a few months ago which bumped savon, maybe the dependency could be removed thanks to that.
Feel free to open a PR if you find a fix though.

Just a heads up - We are going to get rid of Savon to use the recent REST APIs from Responsys in a major version bump. Most of the work has been done, we now need to do a full round of internal testing probably starting next month.

Stay tuned and :star: the project!

**Comment by prashantrajan** [comment]
I would love to help you test out the REST version. I'm  just about to start Responsys integration for our company and we're considering building out a gem that works with the REST APIs but would love to contribute to this project if it's switching to REST

**Comment by florrain** [comment]
Check out [this branch](https://github.com/dandemeyere/responsys-api/tree/migration-to-rest-apis) for the work we've been doing and a more detailed README.

The structure has been reworked and cleaned up as much as possible with breaking changes.
The idea is to get a good test coverage first and then validate integration scenarios.

If you want to work on something specific please create a new issue, that would be much appreciated!
