### ISSUE TITLE
REST WIP branch

### ISSUE THREAD

**Issue by atomical** [dandemeyere/responsys-api#36]
Hi,

The REST branch is marked as as work in progress. Should we use this? Are there known limitations or bugs?

**Comment by florrain** [comment]
Hi @atomical 

That REST implementation hasn't been tested in a production environment yet. At this point, I wouldn't recommend to use it if you're planning on doing an integration. I want to finish a first version of it and release a beta version for people to test and give feedback but haven't dedicated time for it yet.

You'll notice in the PR #35 that most of the `master` version has been rewritten and so even though the code is decently covered in terms of tests, bugs and data inconsistency issues might come up.

At thredUP, we've been using the latest version for a while now without any major noticed bugs. It's using the SOAP servers but it still works!
