### ISSUE TITLE
Update gem dependencies

### ISSUE THREAD

**Issue by jclif** [dandemeyere/responsys-api#40]
Many newer gems are using Connection Pool v2.2. It would be nice if this gem could update that particular dependency. Is anyone else running into this dependency issue?

**Comment by florrain** [comment]
Hi @jclif ! The version for that dependency is very strict and I think we could relax it to 2.x.x for example. Can you open a PR please?

**Comment by jclif** [comment]
@florrain Cut a PR 😄 looks like tests are green on 2.3.3

**Comment by jclif** [comment]
@florrain Also, I confirmed that my fork allows me to update my project's other dependencies successfully! Would there be any chance for a version bump in the near future?

**Comment by florrain** [comment]
@jclif - sure, your PR was merged and a new version ([`0.3.0`](https://rubygems.org/gems/responsys-api/versions/0.3.0)) was published as well. Thanks for doing this!
