### ISSUE TITLE
nokogiri security issues 1615 & 1634

### ISSUE THREAD

**Issue by alexcopquin** [dandemeyere/responsys-api#44]
To address these:
[nokogiri issue 1615](https://github.com/sparklemotion/nokogiri/issues/1615)
[nokogiri issue 1634](https://github.com/sparklemotion/nokogiri/issues/1634)

the version of nokogiri must be updated to > `1.7.2`

**Comment by florrain** [comment]
The version in the gemspec don't need to be that strict honestly. The application using the GEM can make that decision and force nokogiri at a specific version.

So I'd say any version before the major version `< 2.0.0` is acceptable. Would you be up for a PR for that?

**Comment by alexcopquin** [comment]
Sure! I'd be glad to do so. BTW, when is current master going to be released?

**Comment by florrain** [comment]
Thanks! Answered your question in your PR, I'll close this issue.
